### ISSUE TITLE
IDE Fatal Error in 2019.1

### ISSUE THREAD

**Issue by seagullmouse** [denofevil/AureliaStorm#36]
Not sure what causes this in the editor but the plugin is throwing errors in the version 2019.1.

**Exception in plugin AureliaStorm (0.8)...**
```
java.lang.IllegalStateException: hostFile.virtualFile must not be null
	at com.github.denofevil.aurelia.FrameworkHandler.findController(FrameworkHandler.kt:41)
	at com.github.denofevil.aurelia.FrameworkHandler.addContextType(FrameworkHandler.kt:20)
	at com.intellij.lang.javascript.psi.resolve.BaseJSSymbolProcessor.<init>(BaseJSSymbolProcessor.java:144)
	at com.intellij.lang.javascript.psi.resolve.WalkUpResolveProcessor.<init>(WalkUpResolveProcessor.java:62)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolveFromIndices(JSReferenceExpressionResolver.java:250)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolveGlobalReference(JSReferenceExpressionResolver.java:172)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:97)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:37)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:2117)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:472)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.getResolveResultsFromQualifier(JSTypeEvaluator.java:1542)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptTypeEvaluator.getResolveResultsFromQualifier(TypeScriptTypeEvaluator.java:588)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$processRefExpr$31(JSTypeEvaluator.java:1494)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluateContext.processExpression(JSEvaluateContext.java:197)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processRefExpr(JSTypeEvaluator.java:1492)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateTypes(JSTypeEvaluator.java:562)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$null$2(JSTypeEvaluator.java:161)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.resetComplexity(JSEvaluatorComplexityTracker.java:60)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$doEvaluateExpressionOrElementTypes$3(JSTypeEvaluator.java:158)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.runWithRecursionGuard(JSTypeEvaluator.java:2845)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.doEvaluateExpressionOrElementTypes(JSTypeEvaluator.java:157)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$evaluateExpressionOrElementTypes$1(JSTypeEvaluator.java:143)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.lambda$processWithEvaluationGuard$46(JSTypeEvaluator.java:2826)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.runWithRecursionGuard(JSTypeEvaluator.java:2845)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.processWithEvaluationGuard(JSTypeEvaluator.java:2820)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateExpressionOrElementTypes(JSTypeEvaluator.java:143)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:135)
	at com.intellij.lang.javascript.psi.resolve.JSTypeEvaluator.evaluateTypes(JSTypeEvaluator.java:124)
	at com.intellij.lang.javascript.completion.JSReferenceCompletionUtil.calcDefaultVariants(JSReferenceCompletionUtil.java:94)
	at com.intellij.lang.javascript.completion.JSReferenceCompletionProvider.addCompletions(JSReferenceCompletionProvider.java:54)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:170)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.lang.javascript.completion.JSCompletionContributor.fillCompletionVariants(JSCompletionContributor.java:97)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:161)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:120)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:60)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:828)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:277)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by seagullmouse** [comment]
Duplicate of #34
